
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3111:3111"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3111
      - HOST=0.0.0.0
    volumes:
      - ./:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker-in-Docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    command: npm start

  worker:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JOB_CONCURRENCY=3
    volumes:
      - ./:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker-in-Docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    command: npm run start:worker
    restart: unless-stopped

volumes:
  redis_data: